// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XoQwBqFcipx1FvryNeGsWoT2Bd7s6d0',
    appId: '1:174558330266:web:9355e58bf7ac9256d2ce23',
    messagingSenderId: '174558330266',
    projectId: 'marketplaceuni-53ad9',
    authDomain: 'marketplaceuni-53ad9.firebaseapp.com',
    storageBucket: 'marketplaceuni-53ad9.appspot.com',
    measurementId: 'G-EMB30F795W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGmanpOAXJEuuQhtN5umX-V9HUQgrLhE',
    appId: '1:174558330266:android:bdd62914624bc3ffd2ce23',
    messagingSenderId: '174558330266',
    projectId: 'marketplaceuni-53ad9',
    storageBucket: 'marketplaceuni-53ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjLf9JIHBIhoB86cGic-2Na70MS09B5w',
    appId: '1:174558330266:ios:2f72fc775f1c5076d2ce23',
    messagingSenderId: '174558330266',
    projectId: 'marketplaceuni-53ad9',
    storageBucket: 'marketplaceuni-53ad9.appspot.com',
    iosClientId: '174558330266-n09r3frt1fjcog7mmlp18tgn07mgpmcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketplaceUni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSjLf9JIHBIhoB86cGic-2Na70MS09B5w',
    appId: '1:174558330266:ios:62373573f0ae0374d2ce23',
    messagingSenderId: '174558330266',
    projectId: 'marketplaceuni-53ad9',
    storageBucket: 'marketplaceuni-53ad9.appspot.com',
    iosClientId: '174558330266-3lrutvtekiqgjojebvg2n9fv0bvm9h1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketplaceUni.RunnerTests',
  );
}
